### ISSUE TITLE
Licence information is missing

### ISSUE THREAD

**Issue by ChristopherStephan** [ai-ro-bo/Rox.Control.Video.Xamarin#31]
Under which licence can we use the nuget package? I could not find any information here or in the NuGet gallery: https://www.nuget.org/packages/Rox.Xamarin.Video/

**Comment by Rod-at-Rox** [comment]
Hi, the package is available under MIT license. The last build was about 4 years ago, I sort of abandoned it when Xamarin.Forms team started developing MediaElement, but 4 years later and it still isn’t release ready (in most opinions), so I am currently doing a rebuild of this nuget which should be released within a few weeks. Basically just brought up to current standards, replaced obsolete methods etc. The new release will be MIT as well, and I will have the license on the nuget correctly.

Cheers, Rod

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
